DOMAIN = "smol"
INTEGRATION_VERSION = "1.0.0"

REFRESH_RATE_IN_MINUTES_ACCOUNT = 360 # 6 hours

CONFIG_VERSION = 1

CONFIG_KIND = "kind"
CONFIG_KIND_ACCOUNT = "account"

CONFIG_ACCOUNT_NAME = "name"
CONFIG_ACCOUNT_USERNAME = "username"
CONFIG_ACCOUNT_PASSWORD = "password"

DATA_CLIENT = "CLIENT"
DATA_CONFIG = "CONFIG"
DATA_ACCOUNT = "ACCOUNT"
DATA_ACCOUNT_COORDINATOR = "ACCOUNT_COORDINATOR"

REPAIR_ACCOUNT_NOT_FOUND = "account_not_found_{}"

COORDINATOR_REFRESH_IN_SECONDS = 60